### ISSUE TITLE
Top bar completely disappear after screensaver turn off the screen

### ISSUE THREAD

**Issue by davideicardi** [romgrk/gnome-hidetopbar#1]
In the last two months (~) I have an issue that seems to be related to the screen saver or something similar. I use the extension without problems, but if I leave the PC I have the screen saver that turn off the monitor. After that I login again and from that moment I cannot see the top bar anymore. Also I don't see any new notifications. It looks like the top bar is no more available (also if I move the mouse on top of course).
This doesn't happen everytimes, but I notice it at least 2 times a day. The only way to restore it is to log out e login again.

Do you have any idea? How can I debug better to give you more info?

Thank you for your work!

**Comment by romgrk** [comment]
This is a fork, not the original extension. Check https://gitlab.gnome.org/tuxor1337/hidetopbar
